# Generated by Django 4.2.5 on 2023-10-16 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0003_alter_booking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default=datetime.date(2023, 10, 16)),
        ),
    ]
