# Generated by Django 4.2.5 on 2023-09-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='gender',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('O', 'Otro')], default='O', max_length=1),
        ),
    ]
