# Generated by Django 4.2.5 on 2023-10-02 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_neighbor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.neighborhood'),
        ),
    ]
