# Generated by Django 4.2.5 on 2023-09-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_neighbor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='apartment',
            field=models.CharField(default='802', max_length=100),
        ),
        migrations.AlterField(
            model_name='neighbor',
            name='name',
            field=models.CharField(default='Benja Marchant', max_length=100),
        ),
    ]
