# Generated by Django 4.2.5 on 2023-10-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_apartment_id_alter_neighborhood_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.apartment'),
        ),
    ]
