# Generated by Django 4.2.5 on 2023-10-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_neighbor_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbor',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
