# Generated by Django 4.2.5 on 2023-10-03 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_superneighbor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperNeighbor',
        ),
        migrations.CreateModel(
            name='SuperNeighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superneighbor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
