# Generated by Django 4.2.5 on 2023-10-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_delete_superneighbor_superneighbor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superneighbor',
            old_name='neighbor',
            new_name='user',
        ),
    ]
