# Generated by Django 4.2.5 on 2023-10-03 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_rename_neighbor_superneighbor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superneighbor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superneighbor', to=settings.AUTH_USER_MODEL),
        ),
    ]
