# Generated by Django 4.2.5 on 2023-09-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_machine_rename_user_booking_neighbor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
