# Generated by Django 4.2.5 on 2023-09-25 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.constants


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0004_remove_booking_date_remove_booking_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='slots',
            field=models.JSONField(default=utils.constants.default_slot_status),
        ),
        migrations.AlterField(
            model_name='booking',
            name='machine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.machine'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='neighbor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
