# Generated by Django 4.2.5 on 2023-09-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_machine_slots_alter_booking_machine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.IntegerField(default=0),
        ),
    ]
