# Generated by Django 4.2.5 on 2023-09-27 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0006_booking_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.machine'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('neighbor', 'machine', 'slot')},
        ),
    ]
